package com.ymotpyrc.swoops.presentation

import com.ymotpyrc.swoops.domain.games.models.PlayerId

data class PlayerStatsUi(
    val playerId: PlayerId,
    val played : Int,
    val wins: Int,
    val losses: Int,
    val goals: Int,
    val fieldGoals: Int,
    val fieldGoalAttempts: Int,
    val threePoints: Int,
    val threePointAttempts: Int,
    val twoPoints: Int,
    val twoPointAttempts: Int,
    val freeThrows: Int,
    val freeThrowAttempts: Int,
    val defensiveRebounds: Int,
    val offensiveRebounds: Int,
    val rebounds: Int,
    val assists: Int,
    val steals: Int,
    val blocks: Int,
    val fouls: Int,
    val points: Int,
    val turnovers: Int,
    val fieldGoalsPerGame: Float,
    val fieldGoalAttemptsPerGame: Float,
    val fieldGoalPercentagePerGame: Float,
    val threePointsPerGame: Float,
    val threePointAttemptsPerGame: Float,
    val threePointPercentagePerGame: Float,
    val twoPointsPerGame: Float,
    val twoPointAttemptsPerGame: Float,
    val twoPointPercentagePerGame: Float,
    val freeThrowsPerGame: Float,
    val freeThrowAttemptsPerGame: Float,
    val freeThrowPercentagePerGame: Float,
    val defensiveReboundsPerGame: Float,
    val offensiveReboundsPerGame: Float,
    val reboundsPerGame: Float,
    val assistsPerGame: Float,
    val stealsPerGame: Float,
    val blocksPerGame: Float,
    val foulsPerGame: Float,
    val pointsPerGame: Float,
    val turnoversPerGame: Float,
    val trueShootingPercentage: Float,
)
