package com.ymotpyrc.swoops.domain.games.models

data class LineupPlayerStats(
    val playerId: Int,
    val teamId: TeamId,
    val wins: Int,
    val losses: Int,
    val fullName: String,
    val age: Int,
    val starRating: Int,
    val g: String?,
    val fieldGoals: String?,
    val fieldGoalAttempts: String?,
    val fieldGoalPercentage: String?,
    val threePoints: String?,
    val threePointAttempts: String?,
    val threePointPercentage: String?,
    val twoPoints: String?,
    val twoPointAttempts: String?,
    val twoPointPercentage: String?,
    val freeThrows: String?,
    val freeThrowAttempts: String?,
    val freeThrowPercentage: String?,
    val defensiveReboundsPerGame: String?,
    val offensiveReboundsPerGame: String?,
    val reboundsPerGame: String?,
    val assistsPerGame: String?,
    val stealsPerGame: String?,
    val blocksPerGame: String?,
    val foulsPerGame: String?,
    val pointsPerGame: String?,
    val turnoversPerGame: String?,
)
